export const REFLECTION_PROMPTS = [
    "What is a small victory you celebrated recently?",
    "What is one thing you're looking forward to this week?",
    "Describe a moment today that made you smile.",
    "What is a challenge you're currently facing, and how are you handling it?",
    "Who is someone you're grateful for today, and why?",
    "What is a lesson you've learned in the last month?",
    "If you could give your younger self one piece of advice, what would it be?",
    "What does a 'perfect' day look like to you?",
    "What is a habit you'd like to cultivate or break?",
    "What is something you've discovered about yourself recently?",
    "What is a fear you've overcome, or one you're working on?",
    "Describe a place where you feel most at peace.",
    "What is a goal you're working towards right now?",
    "What is something you're proud of, but don't often talk about?",
    "How do you handle stress or overwhelm?",
    "What is a book, movie, or song that has influenced you significantly?",
    "What does 'success' mean to you at this stage of your life?",
    "What is a quality you admire in others?",
    "If you had an extra hour every day, how would you spend it?",
    "What is something you're curious about right now?",
    "How have you changed in the last year?",
    "What is a mistake you've made that turned into a learning opportunity?",
    "What is your favorite way to practice self-care?",
    "What is a dream you've had recently, and what do you think it means?",
    "What is something you're looking forward to in the next year?",
    "How do you define 'happiness'?",
    "What is a quote or mantra that resonates with you?",
    "What is a talent or skill you'd like to learn?",
    "Describe a person who has had a positive impact on your life.",
    "What is something you've done recently that pushed you out of your comfort zone?",
    "How do you stay motivated when things get tough?",
    "What is a simple pleasure you enjoy every day?",
    "What is a value that is important to you?",
    "If you could travel anywhere right now, where would you go?",
    "What is something you've let go of recently?",
    "What is a question you've been asking yourself lately?",
    "How do you show love to others?",
    "What is a memory from your childhood that still brings you joy?",
    "What is something you've forgiven yourself for?",
    "What is a project or idea you're excited about?",
    "How do you find balance in your life?",
    "What is something you've learned from a difficult situation?",
    "What is a compliment you've received that stayed with you?",
    "How do you handle criticism or feedback?",
    "What is a tradition you cherish?",
    "What is something you're grateful for in your physical environment?",
    "How do you start your day to set a positive tone?",
    "What is a regret you've turned into a lesson?",
    "What is something you've done recently that made someone else happy?",
    "How do you define 'inner peace'?",
    "What is a hobby or activity that makes you lose track of time?",
    "What is something you've gained perspective on recently?",
    "How do you stay true to yourself in a world of expectations?",
    "What is a gift you've received that was particularly meaningful?",
    "What is something you've learned about a friend or family member recently?",
    "How do you celebrate your achievements, big or small?",
    "What is a boundary you've set for yourself lately?",
    "What is something you've seen or heard lately that inspired you?",
    "How do you nurture your creativity?",
    "What is a risk you've taken that paid off?",
    "What is something you've changed your mind about recently?",
    "How do you practice mindful presence?",
    "What is a strength you've discovered in yourself during a hard time?",
    "What is something you've contributed to your community?",
    "How do you handle transitions or changes in your life?",
    "What is a mystery or unknown you're comfortable with?",
    "What is something you've learned from a younger person?",
    "How do you keep your mind sharp and engaged?",
    "What is a burden you've shared with someone else?",
    "What is something you've found beauty in today?",
    "How do you define 'integrity'?",
    "What is a promise you've made to yourself?",
    "What is something you've learned from an older person?",
    "How do you stay connected to your intuition?",
    "What is a piece of art that moved you deeply?",
    "What is something you've accomplished that you once thought was impossible?",
    "How do you show yourself compassion?",
    "What is a conversation that changed your perspective?",
    "What is something you've done that required a lot of courage?",
    "How do you handle failure?",
    "What is a small act of kindness you witnessed recently?",
    "What is something you've realized about your health or well-being?",
    "How do you cultivate a sense of awe or wonder?",
    "What is a difficult decision you've made recently?",
    "What is something you've learned from a nature experience?",
    "How do you define 'community'?",
    "What is a piece of advice you've given that you also needed to hear?",
    "What is something you've done that made you feel truly alive?",
    "How do you keep your curiosity alive?",
    "What is a silence you've appreciated recently?",
    "What is something you've built or created from scratch?",
    "How do you handle disappointment?",
    "What is a lesson you've learned from a pet or animal?",
    "What is something you've noticed about your growth over the years?",
    "How do you practice gratitude when things are hard?",
    "What is a risk you didn't take, and what did you learn?",
    "What is something you've done that felt like 'it was meant to be'?",
    "How do you define 'freedom'?",
    "What is a story you tell yourself that you'd like to change?",
    "What is something you've done today to invest in your future self?"
];
